import { proofStats as fallbackStats, logos as fallbackLogos } from '@/data/home';
import { Section, Label } from '@/components/ui/primitives';
import { CountUp, Reveal, useDirectionalReveal } from '@/components/ui/ScrollMotion';
import { useCmsRecord } from '@/lib/cms';
export default function Proof(){
  const ribbon=useCmsRecord('homepage','ribbon').record?.content??{};
  const proof=useCmsRecord('homepage','proof').record?.content??{};
  const logos=Array.isArray(ribbon.items)?ribbon.items.map(String):fallbackLogos;
  const stats=Array.isArray(proof.stats)?proof.stats as {value:string;label:string}[]:fallbackStats;
  const statement=useDirectionalReveal<HTMLParagraphElement>();
  return <><section className="overflow-hidden border-y border-grid bg-yellow py-4 text-dark"><div className="marquee flex w-max gap-12 whitespace-nowrap text-xs font-bold uppercase tracking-[.18em]">{[...logos,...logos].map((l,i)=><span key={i}>{l} <b className="ml-12">✳</b></span>)}</div></section><Section id="about" className="bg-[color:var(--background)]"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr] md:items-start"><div><Label>Built for the brave</Label><p ref={statement.ref} className={`direction-reveal from-left display max-w-lg text-4xl font-semibold md:text-6xl ${statement.visible?'is-visible':''}`}>{String(proof.statement??'The ad should feel like culture. The result should feel like math.')}</p></div><Reveal delay={120}><div className="md:pt-16"><p className="max-w-2xl text-sm leading-6 text-muted">{String(proof.supportingCopy??"Most agencies choose between creative and performance. We don't. CLYX connects the instinct that makes people stop with the systems that make brands grow.")}</p><a href="#contact" className="mt-8 inline-flex items-center gap-3 border-b border-foreground pb-2 text-sm font-semibold leading-6 tracking-[.04em]">Meet the team <span>↗</span></a></div></Reveal></div></Section><section className="stats-strip bg-blue text-white"><div className="container grid grid-cols-3">{stats.map((s,i)=><Reveal key={s.label} delay={i*120}><div className={`border-white/25 py-12 md:py-16 ${i<2?'border-r':''} ${i?'md:pl-10':''}`}><div className="display text-6xl font-bold md:text-8xl"><CountUp value={s.value}/></div><p className="mt-3 text-xs font-semibold uppercase tracking-[.16em] text-white/75">{s.label}</p></div></Reveal>)}</div></section></>}
